package com.ninjabird.firelight.content.events
{
    import flash.events.Event;

    /**
     * The event data supplied when a content file has failed to load from an archive.
     */
    public final class FileLoadErrorEvent extends Event
    {
        /**
         * The filename of the loaded file within the archive.
         */
        public var filename:String;

        /**
         * A description of the error that occurred.
         */
        public var errorMessage:String;

        /**
         * Constructor function for an event type raised when a file has failed to load from an archive.
         * @param name The filename of the loaded file within the archive.
         * @param error The error message generated by the loader.
         * @param type The name of the event.
         * @param bubbles true if the event will bubble up.
         * @param cancelable true if the event is cancelable.
         */
        public function FileLoadErrorEvent(file:String, error:String, type:String=ContentEvent.FILE_ERROR, bubbles:Boolean=false, cancelable:Boolean=false)
        {
            super(type, bubbles, cancelable);
            this.filename     = file;
            this.errorMessage = error;
        }

        /**
         * Creates a new event instance with the same fields as this instance.
         * @return A new FileLoadErrorEvent instance.
         */
        override public function clone() : Event
        {
            return new FileLoadErrorEvent(this.filename, this.errorMessage, type, bubbles, cancelable);
        }
    }
}
