package com.ninjabird.firelight.time
{
    /**
     * Defines the interface to an abstraction for a source of time values.
     * Values could be generated by a real clock, time values saved to a file,
     * and so on.
     */
    public interface TimeSource
    {
        /**
         * Reads the current time value.
         * @return The current timestamp, specified in seconds.
         */
        function readCurrentTime() : Number;
    }
}
